---
- include_tasks: vars.yml

- include_tasks: install_ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install_el.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: init.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: systemd.yml
- include_tasks: config.yml
